### ISSUE TITLE
Can't Download Embedded Videos

### ISSUE THREAD

**Issue by willywaggler** [ManoloZocco/Panopto-Video-Downloader#6]
Hi,

First of all, thanks so much for this great tool! Just one problem: it only seems to work on non-embedded videos (i.e., ones whose URL looks like panopto.eu/Panopto/Pages/**Viewer**) and not on embedded ones (i.e., ones whose URL looks like panopto.eu/Panopto/Pages/**Embed**). Clicking on the green button on embedded videos just does nothing; it doesn't bring up Windows Explorer asking you where you want to save it, nor does it give the error message that you get on non-Panopto sites. Refreshing the page doesn't seem to do anything. If you could help me out with this I'd be delighted!

**Comment by ManoloZocco** [comment]
Hi! thanks for using my extension. I think it's fixed now :)

**Comment by willywaggler** [comment]
Hi. Thanks for trying to fix this! Unfortunately, now when I click the button it seems to just refresh the page (I imagine it's trying to go to a Viewer.aspx page but that doesn't work so it just brings me back to the Embed.aspx), and I'm still unable to download the video.
